# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6becc95fe7bebf556245cee1f5afbdebc1f83f648953cd4ccd71e02b2168c333934f0f961638ec1d92c443a8469eee3a03bddc3a242f8e6bb6cf559c9ed9331

test:
  secret_key_base: 46f7721407207abccc35f93fce6f6d094138d78e0bdd3e0d8d93c693f4824677c704074f1507b248d217a5d2a1f096c5723027463461606f3e56c005b99ad5a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
